# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # --- Directorio sincronizado --- 
  config.vm.synced_folder "sync","/directorio_sincronizado"


  config.vm.define :servidor do |servidor|
    servidor.vm.box = "bento/ubuntu-22.04"
    servidor.vm.network :private_network, ip: "192.168.56.3"
    servidor.vm.hostname = "servidor"
    servidor.vm.network "forwarded_port", guest: 8500, host: 8500

    # --- Asignación de recurosos servidor ---
    servidor.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "1"
    end
    # --- APROVISIONAMIENTO DEL SERVIDOR ---
    servidor.vm.provision "shell", path: "provision-servidor.sh"
  end



  config.vm.define :cliente do |cliente|
    cliente.vm.box = "bento/ubuntu-22.04"
    cliente.vm.network :private_network, ip: "192.168.56.2"
    cliente.vm.hostname = "cliente"

    # -- asignacion de recursos cliente
    cliente.vm.provider "virtualbox" do |vb|
      vb.memory = "600"
      vb.cpus = "1"
    end
    # --- APROVISIONAMIENTO DEL CLIENTE ---
    cliente.vm.provision "shell", path: "provision-cliente.sh"
  end
end
